# Generated by Django 3.0.3 on 2020-02-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
