# Generated by Django 3.0.3 on 2020-02-21 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymac', '0002_product_old_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.CharField(max_length=1300),
        ),
    ]
