# Generated by Django 3.0.3 on 2020-02-21 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymac', '0004_auto_20200221_2349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='query',
            new_name='msg',
        ),
    ]
