# Generated by Django 3.1.1 on 2020-12-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymac', '0010_auto_20200317_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('username', models.CharField(default='', max_length=70)),
                ('password', models.CharField(default='', max_length=70)),
                ('phone', models.IntegerField(default='')),
            ],
        ),
    ]
